// dummy_data.js

const LOGOS = {
    mercedes:
        "https://upload.wikimedia.org/wikipedia/commons/f/fb/Mercedes_AMG_Petronas_F1_Logo.svg",
    ferrari:
        "https://upload.wikimedia.org/wikipedia/commons/d/d1/Ferrari-Logo.svg",
    redbull:
        "https://upload.wikimedia.org/wikipedia/en/e/e0/Red_Bull_Racing_logo.svg",
    mclaren:
        "https://upload.wikimedia.org/wikipedia/en/6/66/McLaren_Racing_logo.svg",
    racingpoint:
        "https://upload.wikimedia.org/wikipedia/en/f/f9/Racing_Point_logo.svg",
    renault:
        "https://upload.wikimedia.org/wikipedia/en/1/1b/Renault_F1_Team_logo_2019.svg",
    alphatauri:
        "https://upload.wikimedia.org/wikipedia/commons/1/11/Scuderia_AlphaTauri_logo.svg",
    alfaromeo:
        "https://upload.wikimedia.org/wikipedia/commons/3/30/Alfa_Romeo_Racing_logo.svg",
    haas: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Haas_F1_Team_logo.svg",
    williams:
        "https://upload.wikimedia.org/wikipedia/commons/a/ab/Williams_Racing_2020_logo.svg",
};

export const dummyHeader = {
    track: "British Grand Prix - Silverstone",
    lap: "Lap 12 / 52",
    isConnected: true,
};

// Full 2020 Grid
export const dummyDrivers = [
    {
        i: 0,
        p: 1,
        raceNum: 44,
        name: "L. Hamilton",
        teamId: 0,
        teamName: "Mercedes",
        logo: LOGOS.mercedes,
        interval: 0,
        s1: 28.123,
        s2: 35.456,
        s3: 23.89,
        lt: 87.469,
    },
    {
        i: 1,
        p: 2,
        raceNum: 77,
        name: "V. Bottas",
        teamId: 0,
        teamName: "Mercedes",
        logo: LOGOS.mercedes,
        interval: 1.205,
        s1: 28.15,
        s2: 35.5,
        s3: 23.9,
        lt: 87.55,
    },
    {
        i: 2,
        p: 3,
        raceNum: 33,
        name: "M. Verstappen",
        teamId: 2,
        teamName: "Red Bull",
        logo: LOGOS.redbull,
        interval: 3.45,
        s1: 28.21,
        s2: 35.6,
        s3: 23.95,
        lt: 87.76,
    },
    {
        i: 3,
        p: 4,
        raceNum: 23,
        name: "A. Albon",
        teamId: 2,
        teamName: "Red Bull",
        logo: LOGOS.redbull,
        interval: 8.9,
        s1: 28.4,
        s2: 35.75,
        s3: 24.1,
        lt: 88.25,
    },
    {
        i: 4,
        p: 5,
        raceNum: 55,
        name: "C. Sainz",
        teamId: 3,
        teamName: "McLaren",
        logo: LOGOS.mclaren,
        interval: 1.12,
        s1: 28.45,
        s2: 35.8,
        s3: 24.1,
        lt: 88.35,
    },
    {
        i: 5,
        p: 6,
        raceNum: 4,
        name: "L. Norris",
        teamId: 3,
        teamName: "McLaren",
        logo: LOGOS.mclaren,
        interval: 0.5,
        s1: 28.46,
        s2: 35.82,
        s3: 24.12,
        lt: 88.4,
    },
    {
        i: 6,
        p: 7,
        raceNum: 16,
        name: "C. Leclerc",
        teamId: 1,
        teamName: "Ferrari",
        logo: LOGOS.ferrari,
        interval: 4.56,
        s1: 28.3,
        s2: 35.75,
        s3: 24.05,
        lt: 88.1,
    },
    {
        i: 7,
        p: 8,
        raceNum: 5,
        name: "S. Vettel",
        teamId: 1,
        teamName: "Ferrari",
        logo: LOGOS.ferrari,
        interval: 1.2,
        s1: 28.4,
        s2: 35.8,
        s3: 24.15,
        lt: 88.35,
    },
    {
        i: 8,
        p: 9,
        raceNum: 11,
        name: "S. Perez",
        teamId: 4,
        teamName: "Racing Point",
        logo: LOGOS.racingpoint,
        interval: 2.85,
        s1: 28.4,
        s2: 35.85,
        s3: 24.15,
        lt: 88.4,
    },
    {
        i: 9,
        p: 10,
        raceNum: 18,
        name: "L. Stroll",
        teamId: 4,
        teamName: "Racing Point",
        logo: LOGOS.racingpoint,
        interval: 0.95,
        s1: 28.42,
        s2: 35.88,
        s3: 24.18,
        lt: 88.48,
    },
    {
        i: 10,
        p: 11,
        raceNum: 3,
        name: "D. Ricciardo",
        teamId: 5,
        teamName: "Renault",
        logo: LOGOS.renault,
        interval: 3.2,
        s1: 28.5,
        s2: 35.9,
        s3: 24.2,
        lt: 88.6,
    },
    {
        i: 11,
        p: 12,
        raceNum: 31,
        name: "E. Ocon",
        teamId: 5,
        teamName: "Renault",
        logo: LOGOS.renault,
        interval: 0.8,
        s1: 28.52,
        s2: 35.92,
        s3: 24.22,
        lt: 88.66,
    },
    {
        i: 12,
        p: 13,
        raceNum: 10,
        name: "P. Gasly",
        teamId: 6,
        teamName: "AlphaTauri",
        logo: LOGOS.alphatauri,
        interval: 5.1,
        s1: 28.6,
        s2: 36.0,
        s3: 24.3,
        lt: 88.9,
    },
    {
        i: 13,
        p: 14,
        raceNum: 26,
        name: "D. Kvyat",
        teamId: 6,
        teamName: "AlphaTauri",
        logo: LOGOS.alphatauri,
        interval: 1.1,
        s1: 28.62,
        s2: 36.05,
        s3: 24.35,
        lt: 89.02,
    },
    {
        i: 14,
        p: 15,
        raceNum: 7,
        name: "K. Raikkonen",
        teamId: 7,
        teamName: "Alfa Romeo",
        logo: LOGOS.alfaromeo,
        interval: 6.5,
        s1: 28.7,
        s2: 36.1,
        s3: 24.4,
        lt: 89.2,
    },
    {
        i: 15,
        p: 16,
        raceNum: 99,
        name: "A. Giovinazzi",
        teamId: 7,
        teamName: "Alfa Romeo",
        logo: LOGOS.alfaromeo,
        interval: 0.7,
        s1: 28.72,
        s2: 36.15,
        s3: 24.45,
        lt: 89.32,
    },
    {
        i: 16,
        p: 17,
        raceNum: 8,
        name: "R. Grosjean",
        teamId: 8,
        teamName: "Haas",
        logo: LOGOS.haas,
        interval: 4.2,
        s1: 28.8,
        s2: 36.2,
        s3: 24.5,
        lt: 89.5,
    },
    {
        i: 17,
        p: 18,
        raceNum: 20,
        name: "K. Magnussen",
        teamId: 8,
        teamName: "Haas",
        logo: LOGOS.haas,
        interval: 1.4,
        s1: 28.85,
        s2: 36.25,
        s3: 24.55,
        lt: 89.65,
    },
    {
        i: 18,
        p: 19,
        raceNum: 63,
        name: "G. Russell",
        teamId: 9,
        teamName: "Williams",
        logo: LOGOS.williams,
        interval: 8.0,
        s1: 28.9,
        s2: 36.3,
        s3: 24.6,
        lt: 89.8,
    },
    {
        i: 19,
        p: 20,
        raceNum: 6,
        name: "N. Latifi",
        teamId: 9,
        teamName: "Williams",
        logo: LOGOS.williams,
        interval: 2.1,
        s1: 28.95,
        s2: 36.35,
        s3: 24.65,
        lt: 89.95,
    },
];

export const dummyTelemetry1 = {
    name: "L. Hamilton",
    raceNum: 44,
    logo: LOGOS.mercedes,
    teamName: "Mercedes",
    teamId: 0,
    t: 0.2,
    b: 0.75,
    s: 119,
    g: 3,
    rpm: 8200,
    drs: 1,
};

export const dummyTelemetry2 = {
    name: "M. Verstappen",
    raceNum: 33,
    logo: LOGOS.redbull,
    teamName: "Red Bull",
    teamId: 2,
    t: 1.0,
    b: 0.0,
    s: 298,
    g: 8,
    rpm: 12100,
    drs: 1,
};
